name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --info

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk  
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Decode google-services.json
        env:
          NMEDIA_SECRET: ${{ secrets.NMEDIA_SECRET }}
        run: echo $NMEDIA_SECRET > app/google-services.json

      - name: Run unit testing
        run:
         ./gradlew test
